version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - db-data:/var/lib/docker/volumes
  app:
    image: buonpheaktra/project_repository:1.0
    ports:
      - 5001:3000

volumes:
  db-data:
    driver: local
