version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: schoolManagement
    volumes:
      - myVolume:/var/lib/docker/volumes
  app:
    image: buonpheaktra/project_repository:pg-node-express-1.0.1
    ports:
      - 5001:3000

volumes:
  myVolume:
    driver: local
 